import type { LocalizationResource } from '@clerk/types'

export const ruRU: LocalizationResource = {
  locale: 'ru-RU',
  unstable__errors: {
    already_a_member_in_organization: '{{email}} уже является участником организации.',
    captcha_invalid: 'Неверная капча',
    captcha_unavailable:
        'Регистрация не удалась из-за неудачной проверки на бота. Пожалуйста, обновите страницу, чтобы попробовать снова, или обратитесь в службу поддержки за помощью.',
    form_code_incorrect: 'Неверный код',
    form_identifier_exists__email_address: 'Этот email уже используется',
    form_identifier_exists__phone_number: 'Этот номер телефона уже используется',
    form_identifier_exists__username: 'Это имя пользователя уже занято',
    form_identifier_not_found: 'Аккаунт не найден',
    form_param_format_invalid: 'Неверный формат',
    form_param_format_invalid__email_address: 'Неверный формат email',
    form_param_format_invalid__phone_number: 'Неверный формат номера телефона',
    form_param_max_length_exceeded__first_name: 'Имя слишком длинное',
    form_param_max_length_exceeded__last_name: 'Фамилия слишком длинная',
    form_param_max_length_exceeded__name: 'Название слишком длинное',
    form_param_nil: 'Обязательное поле',
    form_param_type_invalid: 'Неверный тип данных',
    form_param_type_invalid__email_address: 'Неверный тип email',
    form_param_type_invalid__phone_number: 'Неверный тип номера телефона',
    form_param_value_invalid: 'Неверное значение',
    form_password_incorrect: 'Неверный пароль',
    form_password_length_too_short: 'Ваш пароль слишком короткий. Он должен содержать не менее 8 символов.',
    form_password_not_strong_enough: 'Ваш пароль недостаточно надежный.',
    form_password_pwned:
        'Этот пароль был обнаружен в утечке данных и не может быть использован, пожалуйста, попробуйте другой пароль.',
    form_password_pwned__sign_in:
        'Этот пароль был обнаружен в утечке данных и не может быть использован, пожалуйста, сбросьте ваш пароль.',
    form_password_size_in_bytes_exceeded: 'Пароль слишком длинный',
    form_password_validation_failed: 'Ошибка проверки пароля',
    form_username_invalid_character: 'Недопустимый символ в имени пользователя',
    form_username_invalid_length: 'Ваше имя пользователя должно содержать от {{min_length}} до {{max_length}} символов.',
    identification_deletion_failed: 'Не удалось удалить идентификатор',
    not_allowed_access: 'Доступ запрещен',
    organization_domain_blocked: 'Этот домен заблокирован',
    organization_domain_common: 'Этот домен слишком распространен',
    organization_domain_exists_for_enterprise_connection: 'Домен уже используется корпоративным подключением',
    organization_membership_quota_exceeded: 'Превышена квота участников организации',
    organization_minimum_permissions_needed: 'Недостаточно прав',
    organization_not_found_or_unauthorized:
        'Вы больше не являетесь участником этой организации. Пожалуйста, выберите или создайте другую.',
    organization_not_found_or_unauthorized_with_create_organization_disabled:
        'Вы больше не являетесь участником этой организации. Пожалуйста, выберите другую.',
    passkey_already_exists: 'Ключ доступа (passkey) уже зарегистрирован на этом устройстве.',
    passkey_not_supported: 'Ключи доступа (passkeys) не поддерживаются на этом устройстве.',
    passkey_pa_not_supported: 'Для регистрации требуется платформенный аутентификатор, но устройство его не поддерживает.',
    passkey_registration_cancelled: 'Регистрация ключа доступа (passkey) была отменена или превышено время ожидания.',
    passkey_retrieval_cancelled: 'Проверка ключа доступа (passkey) была отменена или превышено время ожидания.',
    passwordComplexity: {
      maximumLength: 'менее {{length}} символов',
      minimumLength: '{{length}} или более символов',
      requireLowercase: 'строчную букву',
      requireNumbers: 'цифру',
      requireSpecialCharacter: 'специальный символ',
      requireUppercase: 'заглавную букву',
      sentencePrefix: 'Ваш пароль должен содержать',
    },
    phone_number_exists: 'Номер телефона уже существует',
    session_exists: 'Сессия уже существует',
    web3_missing_identifier: 'Расширение Web3 Кошелька не найдено. Пожалуйста, установите его, чтобы продолжить.',
    zxcvbn: {
      couldBeStronger: 'Ваш пароль работает, но может быть надежнее. Попробуйте добавить больше символов.',
      goodPassword: 'Ваш пароль соответствует всем необходимым требованиям.',
      notEnough: 'Ваш пароль недостаточно надежный.',
      suggestions: {
        allUppercase: 'Напишите некоторые, но не все буквы заглавными.',
        anotherWord: 'Добавьте больше слов, которые менее распространены.',
        associatedYears: 'Избегайте лет, которые связаны с вами.',
        capitalization: 'Используйте заглавные буквы не только для первой буквы.',
        dates: 'Избегайте дат и лет, которые связаны с вами.',
        l33t: 'Избегайте предсказуемых замен букв, таких как «@» для «a».',
        longerKeyboardPattern: 'Используйте более длинные шаблоны клавиш и несколько раз меняйте направление ввода.',
        noNeed: 'Вы можете создавать надежные пароли без использования символов, цифр или заглавных букв.',
        pwned: 'Если вы используете этот пароль в другом месте, вам следует изменить его.',
        recentYears: 'Избегайте последних лет.',
        repeated: 'Избегайте повторяющихся слов и символов.',
        reverseWords: 'Избегайте обратного написания распространенных слов.',
        sequences: 'Избегайте распространенных последовательностей символов.',
        useWords: 'Используйте несколько слов, но избегайте распространенных фраз.',
      },
      warnings: {
        common: 'Это commonly used password.',
        commonNames: 'Распространенные имена и фамилии легко угадать.',
        dates: 'Даты легко угадать.',
        extendedRepeat: 'Повторяющиеся шаблоны символов, такие как "abcabcabc", легко угадать.',
        keyPattern: 'Короткие шаблоны клавиш легко угадать.',
        namesByThemselves: 'Отдельные имена или фамилии легко угадать.',
        pwned: 'Ваш пароль был раскрыт в результате утечки данных в Интернете.',
        recentYears: 'Последние годы легко угадать.',
        sequences: 'Распространенные последовательности символов, такие как "abc", легко угадать.',
        similarToCommon: 'Это похоже на commonly used password.',
        simpleRepeat: 'Повторяющиеся символы, такие как "aaa", легко угадать.',
        straightRow: 'Прямые ряды клавиш на клавиатуре легко угадать.',
        topHundred: 'Это часто используемый пароль.',
        topTen: 'Это очень часто используемый пароль.',
        userInputs: 'Не должно быть никаких личных или связанных со страницей данных.',
        wordByItself: 'Отдельные слова легко угадать.',
      },
    },
  },
} as const