export const lorem = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed scelerisque urna vel rhoncus euismod. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed vitae tempor dolor. Aliquam erat volutpat. Ut metus purus, vestibulum eu ante vel, placerat finibus dolor. Donec vitae accumsan leo, eu venenatis nulla. Vestibulum et hendrerit ante.\n' +
    '\n' +
    'Praesent accumsan magna eget est egestas bibendum. Suspendisse non massa ut eros faucibus ultrices. Ut ante neque, semper vel nulla consequat, vulputate convallis elit. Ut non mi sed elit elementum vestibulum sit amet et velit. Donec tortor enim, suscipit a rutrum a, pharetra ut metus. Curabitur cursus magna vel dolor maximus mollis pulvinar in metus. Nam id pulvinar velit. Donec sagittis accumsan augue, a interdum dolor ullamcorper vitae. Integer at metus ipsum.\n' +
    '\n' +
    'Sed fringilla felis et ornare molestie. Ut posuere eget lacus ac consectetur. Vestibulum quis finibus justo. Ut convallis tellus a quam tincidunt, vitae blandit urna lacinia. Aliquam id tempor magna. Cras eleifend enim sit amet tincidunt feugiat. Fusce id eleifend odio, eget sollicitudin magna. Mauris fermentum nibh nec elit egestas, et luctus odio ornare. Donec malesuada facilisis tortor, non hendrerit odio molestie id. Fusce suscipit magna eget magna eleifend dapibus. Vivamus sollicitudin eget nunc nec luctus. Aenean tempus libero non viverra tempor. Donec et massa quis dui dictum rutrum eget in tortor. Fusce gravida viverra leo, et ornare dolor venenatis et.\n' +
    '\n' +
    'Nam feugiat purus vitae elit aliquam scelerisque. Aliquam erat volutpat. Nulla imperdiet, turpis pharetra imperdiet rutrum, est tellus varius neque, id porttitor augue lectus a ante. Donec a leo ipsum. Maecenas metus purus, sollicitudin quis mattis ut, varius sed nunc. Cras venenatis id nisl sit amet tincidunt. Nulla facilisi. Nam a lectus gravida dui dictum eleifend id at neque. Etiam rutrum dolor nec est elementum euismod. Interdum et malesuada fames ac ante ipsum primis in faucibus. Integer a turpis eu quam pellentesque mollis eget vel lectus. Vestibulum felis turpis, vestibulum at sapien eu, varius porttitor ligula. Aenean at lacus id sem convallis consequat ut eu urna. Nullam viverra libero non varius mattis.\n' +
    '\n' +
    'Cras justo tortor, lacinia at luctus in, fringilla eget enim. Sed tempor vulputate interdum. Proin eu dui magna. Proin consectetur mattis eleifend. Donec nec lacus cursus, ornare mauris nec, rutrum lorem. Donec dolor dui, vehicula eu porta condimentum, auctor ut velit. Curabitur sed placerat erat. Pellentesque vehicula bibendum odio sed dictum. Vestibulum fringilla tincidunt odio quis dignissim. Integer luctus eget eros id bibendum.\n' +
    '\n' +
    'Integer dignissim vitae mauris vitae viverra. Nunc fermentum, tortor tempor euismod cursus, metus orci tempus purus, in volutpat nulla ante et nulla. Sed suscipit mauris sapien, et imperdiet neque porta at. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec vel convallis augue. Vestibulum sollicitudin iaculis erat nec tincidunt. Praesent pellentesque nisi pharetra, convallis metus nec, ornare lacus. Maecenas at quam leo. Donec at purus lobortis, dictum augue varius, sagittis sapien. Aenean varius mi eu ligula venenatis placerat. Phasellus ac mi nec eros lacinia sagittis vitae a turpis. Quisque accumsan leo justo, consectetur facilisis quam malesuada id. Sed semper libero nulla, suscipit tempor magna gravida et. Etiam laoreet neque sapien, sed suscipit augue consectetur sed. Pellentesque a eros nec arcu maximus rutrum. Sed id euismod felis.\n' +
    '\n' +
    'Aenean quis volutpat neque. In quis consectetur elit, quis rutrum orci. Phasellus non fringilla sapien, vel gravida metus. Praesent vitae diam vulputate, accumsan sem a, eleifend neque. Sed hendrerit et est nec mollis. Nullam a fermentum nisl. Fusce imperdiet elementum dapibus. Pellentesque metus magna, pulvinar eget enim at, iaculis interdum lectus. Sed ac tellus non augue viverra egestas.\n' +
    '\n' +
    'Fusce lobortis tempus leo, ut congue odio aliquet ac. Donec arcu dolor, mollis sit amet lobortis eu, pretium at ex. Vivamus mi dui, scelerisque in sem placerat, semper egestas nisi. Ut vehicula leo sit amet convallis pulvinar. Quisque sit amet volutpat quam, vel eleifend est. Sed ut dui mauris. Fusce ipsum nunc, efficitur et tempus eget, vehicula et dolor. Aliquam varius tortor non tincidunt ultricies.\n' +
    '\n' +
    'Nunc nec neque bibendum, sagittis dui at, accumsan ex. Etiam in dignissim lacus. Integer sodales ut neque sed dapibus. Vestibulum ac auctor lacus. Pellentesque fermentum cursus eros vitae cursus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vivamus lectus felis, tincidunt vitae velit et, dapibus vulputate arcu.\n' +
    '\n' +
    'Sed congue dapibus accumsan. Sed sagittis ante risus, nec sodales erat gravida vel. Nullam blandit, est sit amet faucibus condimentum, erat risus fermentum arcu, nec mattis erat justo vitae ligula. Nullam egestas arcu a lorem sollicitudin, vel aliquet quam efficitur. Cras lobortis fringilla arcu, sed aliquet risus dignissim nec. Mauris sagittis, magna eget tempor dictum, justo erat auctor metus, et malesuada mauris enim ac magna. Pellentesque aliquet lorem vel leo mollis varius. Aliquam dapibus sit amet enim sed suscipit. Sed ligula tellus, fringilla nec tristique at, euismod in augue. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse cursus tincidunt sollicitudin. Mauris in tincidunt neque. Etiam vel euismod risus, vel dictum leo. Praesent augue est, fringilla eu congue ac, ultrices quis nisl. Nunc vestibulum, ex quis vulputate egestas, justo lectus pretium dolor, ac scelerisque justo nisl a nibh.\n' +
    '\n' +
    'Etiam semper neque a sem aliquet porttitor. In vel justo et dolor cursus porta molestie in dolor. Fusce at eleifend magna. Integer euismod, lorem a finibus aliquam, leo arcu laoreet odio, quis venenatis ante nibh at purus. Pellentesque elementum eget ex eu gravida. Ut consequat lacus nec tincidunt convallis. Sed aliquet facilisis quam non laoreet. Phasellus mollis accumsan nunc. In fringilla fermentum metus, ac consectetur quam feugiat ut. Duis blandit lacus arcu, sed facilisis erat tempus sed. Etiam euismod sagittis elit, maximus vulputate nulla viverra id. Vestibulum viverra nulla est, id tincidunt tortor aliquet sed.\n' +
    '\n' +
    'Morbi eu porttitor arcu. Suspendisse varius, magna nec facilisis elementum, erat sem iaculis mauris, ac consectetur enim ipsum vel ex. Maecenas sed dui non nisl semper euismod. In facilisis dui sem, vel maximus quam tincidunt varius. Integer tristique turpis justo, quis faucibus mi tincidunt ac. Aenean sit amet porttitor tortor, nec sagittis tellus. Quisque in ultricies odio. Donec vel erat sed ante aliquet ultricies. Vivamus varius nunc diam.\n' +
    '\n' +
    'Nunc vestibulum orci nec massa imperdiet hendrerit. Curabitur a convallis purus. Donec ullamcorper leo eget aliquet ultricies. Mauris non pretium tortor. Nulla ac viverra enim, id posuere lacus. Etiam at risus ut magna varius pretium. Etiam bibendum erat vel nibh feugiat semper. Donec a placerat nibh, vitae ullamcorper dolor. Pellentesque lacus urna, venenatis scelerisque rhoncus non, imperdiet vel odio. Integer vestibulum accumsan arcu, et egestas velit condimentum et. Nam convallis gravida velit, vitae mollis augue efficitur sed. Nulla in egestas odio. Aenean tristique dictum sagittis. Ut pulvinar dolor quis dolor gravida, eget sodales nunc efficitur. Phasellus aliquam cursus scelerisque.'